### ISSUE TITLE
Upgrade to Webpack 4 - checklist

### ISSUE THREAD

**Issue by ankurk91** [ankurk91/vue-flatpickr-component#70]
Checklist

### Packages and configs
- [x] install webpack-cli 
- [ ] all loaders are compatible, babel-loader, vue-loader v15
- [x]  replacement of `CommonsChunkPlugin`
- [x] `ModuleConcatenationPlugin` is not required when mode is production
- [x] `UnminifiedWebpackPlugin` compatibility - yes
- [x] `CleanWebpackPlugin` compatibility - yes
- [x] `HtmlWebpackPlugin` compatibility - yes
- [x] `ProvidePlugin` may have new syntax - no
- [x] `HotModuleReplacementPlugin` may have new syntax - 
- [x] webpack 4 has modes `--mode` param
- [x] build configs, library export
- [x] Dev server syntax - set mode to development in command
- [ ] Extract text webpack plugin should be replaced by [this](https://github.com/webpack-contrib/mini-css-extract-plugin) 

### Docs
- [ ] Update any documentation in readme or wiki about webpack

### Testing
- [ ] Test case pases
- [ ] Travis CI
- [x] build files works in browser - without any bundler
- [x] build files works with webpack 3 and 4

### Other
- [x] Requires node js v6.x

###  take help from
* https://medium.com/justfrontendthings/starting-with-webpack-4-and-vuejs-a-quick-start-tutorial-4a244410d55e
* https://medium.com/webpack/webpack-4-mode-and-optimization-5423a6bc597a

**Comment by ismenc** [comment]
Hello,
I didnt get it working on webpack 4 (basic example), isnt it working yet? Also using this dependencies:
```
"buefy": "^0.6.5",
"vue": "^2.5.11",
"vue-flatpickr-component": "^7.0.1"
```
Looks like babel doesnt get to find the css `import 'flatpickr/dist/flatpickr.css';`. I guess its not necesary for working so i commented it.
There only appear a empty imput field

**Comment by ankurk91** [comment]
It is not related to webpack 4.
You need to configure appropriate loader. See this example -
https://github.com/ankurk91/vue-flatpickr-component/blob/d848ffe55e92867fe883f2797fef64694813d3e3/webpack.config.dev.js#L40-L43

**Comment by ankurk91** [comment]
Fixed with 
https://github.com/ankurk91/vue-flatpickr-component/commit/d9b500be1056976957bf5489f7c3a3b0a9d07796
